apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: hello-geek-girls

build:
  artifacts:
    - image: hello-geek-girls
      docker:
        dockerfile: Dockerfile

deploy:
  kubectl:
    manifests:
      - k8s/deployment.yaml  # Always deploy the application

portForward:
  - resourceType: service
    resourceName: hello-geek-girls-service
    port: 80
    localPort: 8080  # Always available

profiles:
  - name: mock
    build:
      artifacts:
        - image: hello-geek-girls  # Make sure the app is built
          docker:
            dockerfile: Dockerfile
        - image: mock-service  # Build the mock service too
          docker:
            dockerfile: mocks/Dockerfile
    deploy:
      kubectl:
        manifests:
          - k8s/deployment.yaml  # Deploy the application
          - k8s/mocks.yaml       # Deploy the mock service
    portForward:
      - resourceType: service
        resourceName: hello-geek-girls-service
        port: 80
        localPort: 8080
      - resourceType: service
        resourceName: mock-service
        port: 8081
        localPort: 8081
