apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: hello-geek-girls
build:
  tagPolicy:
    sha256: {}
  local:
    push: false
  artifacts:
    - image: hello-geek-girls-local
      context: .
      docker:
        dockerfile: app/Dockerfile
deploy:
  kubectl:
    manifests:
      - k8s/app-deployment.yaml 
portForward:
  - resourceType: service
    resourceName: hello-geek-girls-service
    port: 80
    localPort: 8080
