apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-geek-girls
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-geek-girls
  template:
    metadata:
      labels:
        app: hello-geek-girls
    spec:
      containers:
        - name: app
          image: hello-geek-girls-local
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: hello-geek-girls-service
spec:
  selector:
    app: hello-geek-girls
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
