apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-service
  template:
    metadata:
      labels:
        app: mock-service
    spec:
      containers:
        - name: mock
          image: mock-service
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: mock-service
spec:
  selector:
    app: mock-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
